---

- hosts: localhost
  become: true

  pre_tasks:
    - name: "Build hosts file"
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item[1] }}$'
        line: "{{ item[1] }} {{ item[0] }}"
        state: present
      with_items: 
        - [['server', '192.168.50.10'],
           ['fedora', '192.168.50.11'],
           ['windows', '192.168.50.12']]

    - name: Create SSL directory
      file:
        path: /etc/nginx/ssl
        state: directory

    - name: "Save certificates"
      copy:
        src: "/vagrant/provisioning/pki/{{ item }}"
        dest: "/etc/nginx/ssl/{{ item }}"
        mode: 0600
      with_items:
        - "server.crt"
        - "server.key"
        - "dhparams.pem"

  vars_files:
    - "{{ lookup('env', 'VARS_FILE')  }}"

  roles:
    - facts
    - couchdb
    - nodejs
    - preferences-server
    - preferences-server-data-loader
    - nginx
    - nginx-reverse


